error: Property 'city' has no initializer and is not definitely assigned in the constructor.
To fix the error, you need to add definite assignment assertions (!) to the properties of the Weather class.